SaccoD/urls.py
from django.contrib import admin 
from django.urls import path, include

urlpatterns = [
    path('poll/',include('poll.urls')),
    path('tumaini/',include('tumaini.urls')),
    #path('news/',include('news.urls')),
    path('Tumainibase/',include('Tumainibase.urls')),
    path('admin/', admin.site.urls),
]

Tumainibase/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name= 'Tumainibase'

urlpatterns=[
    path('',views.index, name='index'),
    path('registration/',views.registration, name='registration'),    
        
        
        
        
            ]

Tumainibase/models.py
from django.db import models

# Create your models here.

Tumainibase/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request , 'Tumainibase/index.html', {})

def registration(request):
    return render(request , 'Tumainibase/registration.html', {})

Tumainibase/templates/Tumainibase/base.html
<!DOCTYPE html>

<html>
<head>
<title>TUMAINI SACCO</title>

<meta charset="iso-8859-1">
{% load static %}
<link rel="icon" type="image/png" href="{% static 'Tumainibase/favicon-32x32.png' %}" sizes="32x32" />
<link rel="icon" type="image/png" href="{% static 'Tumainibase/favicon-16x16.png' %}" sizes="16x16" /> 
<link rel="stylesheet" href="{% static 'Tumainibase/layout/styles/layout.css' %}" type="text/css">
<script type="text/javascript" src="{% static 'Tumainibase/layout/scripts/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Tumainibase/layout/scripts/jquery-defaultvalue.js' %}"></script>
<!-- homepage slider scripts -->
<link rel="stylesheet" href="{% static 'Tumainibase/layout/scripts/supersized/supersized.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'Tumainibase/layout/scripts/supersized/supersized.shutter.css' %}" type="text/css">
<script  type="text/javascript" src="{% static 'Tumainibase/layout/scripts/supersized/supersized.3.2.7.js' %}"></script>
<script  type="text/javascript" src="{% static 'Tumainibase/layout/scripts/supersized/supersized.shutter.min.js' %}"></script>
<script  type="text/javascript" src="{% static 'Tumainibase/layout/scripts/supersized/supersized.setup.js' %}"></script>
<!-- / homepage slider scripts -->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
    <img src="{% static 'Tumainibase/images/logosacco.png' %}" alt="logo for the sacco"><h1><a href="{%url 'Tumainibase:index' %}">T<span>umaini Sacco</span></a></h1>
      <h2>A sacco you can trust</h2>
    </div>
    <form action="#" method="post">
      <fieldset>
        <legend>Search:</legend>
        <input type="text" value="Search Our Website&hellip;" onFocus="this.value=(this.value=='Search Our Website&hellip;')? '' : this.value ;">
        <input type="image" src="{% static 'Tumainibase/layout/images/search.gif' %}" id="search" alt="Search">
      </fieldset>
    </form>
    <nav>
      <ul class="clear">
        <li class="first active"><a href="{%url 'Tumainibase:index' %}">Home</a></li>
        <li><a href="{% static 'Tumainibase/pages/style-demo.html' %}">Registration</a></li>
        <li><a href="{% static 'Tumainibase/pages/full-width.html' %}">Login</a></li>
        <li><a href="#">Sacco Details</a>
          <ul>
            <li><a href="#">About Us </a></li>
            <li><a href="#">Sacco Investments</a></li>
            <li><a href="#">Contacts </a></li>
          </ul>
        </li>
      <li><a href="{% static 'Tumainibase/pages/gallery.html' %}">Gallery</a></li>
      <li><a href="{% static 'Tumainibase/pages/portfolio.html' %}">Portfolio</a></li>
      </ul>
    </nav>
  </header>
<!-- Footer -->
<div class="wrapper row4">
  <div id="footer" class="clear"> 
    <!-- Section One -->
    <section class="one_quarter first">
      <h2 class="title">Contact Details</h2>
      <p>You can reach us through the following numbers or post a query on our website .</p>
      <p>Tel: 0715912799<br>
        Fax: 0732857369<br>
        Email: <a href="mailto:njerudenis0@gmail.com?Subject=mailfromTumainiSacco">njerudenis0@gmail.com</a></p>
    </section>
    <!-- Section Two -->
    <section class="one_quarter">
      <h2 class="title">Loans</h2>
      <nav>
        <ul>
          <li class="first">Biashara loan</li>
          <li>Makeover loan</li>
          <li>Salary advance</li>
          <li>Insurance premium finance loan</li>
          <li>Emergency loan, School fees loan</li>
        </ul>
      </nav>
    </section>
    <!-- Section Three -->
    <section class="one_quarter">
      <h2 class="title">From The Blog</h2>
      <article>
        <header>
          <h2>Blog Post Title</h2>
          <time datetime="2018-02-01">Thursday, 1<sup>th</sup> Feburuary 2018</time>
        </header>
        <p>One of the best sacco's around have very low rates in their loans and savings plan are the best.</p>
        <p><a href="#">Read More &raquo;</a></p>
      </article>
    </section>
    <!-- Section Four -->
    <section class="one_quarter">
      <h2 class="title">Grab Our Newsletter</h2>
      <form method="post" action="#">
        <fieldset>
          <legend>Contact Form:</legend>
          <label for="nl_name">Name:</label>
          <input type="text" name="nl_name" id="nl_name" value="">
          <label for="nl_email">Email:</label>
          <input type="text" name="nl_email" id="nl_email" value="">
          <button type="submit" value="submit">Submit</button>
        </fieldset>
      </form>
    </section>
    <!-- / Section --> 
  </div>
</div>
<!-- Copyright -->
<div class="wrapper row5">
  <footer id="copyright" class="clear">
    <p class="fl_left">Copyright &copy; 2018 - All Rights Reserved - <a href="#">Tumaini @Co</a></p>
   
  </footer>
</div>
<script>
$(document).ready(function () {
    $("#nl_name, #nl_email").defaultvalue("Name", "Email Address");
});
</script>
</body>
</html>

Tumainibase/templates/Tumainibase/index.html
<!DOCTYPE html>

<html>
<head>
<title>TUMAINI SACCO</title>

<meta charset="iso-8859-1">
{% load static %}
<link rel="icon" type="image/png" href="{% static 'Tumainibase/favicon-32x32.png' %}" sizes="32x32" />
<link rel="icon" type="image/png" href="{% static 'Tumainibase/favicon-16x16.png' %}" sizes="16x16" /> 
<link rel="stylesheet" href="{% static 'Tumainibase/layout/styles/layout.css' %}" type="text/css">
<script type="text/javascript" src="{% static 'Tumainibase/layout/scripts/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Tumainibase/layout/scripts/jquery-defaultvalue.js' %}"></script>
<!-- homepage slider scripts -->
<link rel="stylesheet" href="{% static 'Tumainibase/layout/scripts/supersized/supersized.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'Tumainibase/layout/scripts/supersized/supersized.shutter.css' %}" type="text/css">
<script  type="text/javascript" src="{% static 'Tumainibase/layout/scripts/supersized/supersized.3.2.7.js' %}"></script>
<script  type="text/javascript" src="{% static 'Tumainibase/layout/scripts/supersized/supersized.shutter.min.js' %}"></script>
<script  type="text/javascript" src="{% static 'Tumainibase/layout/scripts/supersized/supersized.setup.js' %}"></script>
<!-- / homepage slider scripts -->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
    <img src="{% static 'Tumainibase/images/logosacco.png' %}" alt="logo for the sacco"><h1><a href="{%url 'Tumainibase:index' %}">T<span>umaini Sacco</span></a></h1>
      <h2>A sacco you can trust</h2>
    </div>
    <form action="#" method="post">
      <fieldset>
        <legend>Search:</legend>
        <input type="text" value="Search Our Website&hellip;" onFocus="this.value=(this.value=='Search Our Website&hellip;')? '' : this.value ;">
        <input type="image" src="{% static 'Tumainibase/layout/images/search.gif' %}" id="search" alt="Search">
      </fieldset>
    </form>
    <nav>
      <ul class="clear">
        <li class="first active"><a href="{%url 'Tumainibase:index' %}">Home</a></li>
        <li><a href="{% static 'Tumainibase/pages/style-demo.html' %}">Registration</a></li>
        <li><a href="{% static 'Tumainibase/pages/full-width.html' %}">Login</a></li>
        <li><a href="#">Sacco Details</a>
          <ul>
            <li><a href="#">About Us </a></li>
            <li><a href="#">Sacco Investments</a></li>
            <li><a href="#">Contacts </a></li>
          </ul>
        </li>
      <li><a href="{% static 'Tumainibase/pages/gallery.html' %}">Gallery</a></li>
      <li><a href="{% static 'Tumainibase/pages/portfolio.html' %}">Portfolio</a></li>
      </ul>
    </nav>
  </header>
</div>
<!-- Slider -->
<div id="sliderwrap">
  <div id="slider"><a href="javascript:void(0)" id="prevslide" class="load-item"></a> <a href="javascript:void(0)" id="nextslide" class="load-item"></a></div>
</div>
<!-- / Slider --> 
<!-- content -->
<div class="wrapper row3">
  <div id="container" class="clear">
    <div id="homepage"> 
      <!-- ########################################################################################## --> 
      <!-- ########################################################################################## --> 
      <!-- Services -->
      <section id="services">
        <ul class="clear">
          <li class="one_quarter first"><img src="{% static 'Tumainibase/images/vision.ico' %}" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Vision</a></h2>
              <p>To be a SACCO that empowers members for improved quality of life.</p>
            </article>
          </li>
          <li class="one_quarter"><img src="{% static 'Tumainibase/images/motto.ico' %}" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Our Motto</a></h2>
              <p>United for prosperity</p>
            </article>
          </li>
          <li class="one_quarter"><img src="{% static 'Tumainibase/images/mission.ico' %}" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Mission</a></h2>
              <p>To facilitate the mobilization of savings and provision of cost effective financial and non-financial products and services to our members and customers in Kenya and beyond.</p>
            </article>
          </li>
          <li class="one_quarter"><img src="{% static 'Tumainibase/images/savings.ico' %}" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Savings</a></h2>
              <p>We have various savings accounts that suits Kenya market.Visit any of our branches country wide and start saving today</p>
            </article>
          </li>
        </ul>
      </section>
      <!-- / Services --> 
      <!-- ########################################################################################## --> 
      <!-- ########################################################################################## --> 
      <!-- Shout -->
      <section id="shout">
        <p><strong>&ldquo; Well managed Sacco's can be the saving grace of the community &bdquo;</strong></p>
      </section>
      <!-- / Shout --> 
      <!-- ########################################################################################## --> 
      <!-- ########################################################################################## --> 
      <!-- Latest -->
      <section id="latest">
        <ul class="clear">
          <li class="one_quarter first">
            <h1>A word from ;</h1>
            <p>Just a few words from  some of the officials in the sacco .</p>
          </li>
          <li class="one_quarter">
            <article>
              <figure><img src="{% static 'Tumainibase/images/admin1.gif' %}" width="225" height="220" alt="">
                <figcaption>
                  <h2>CFO</h2>
                  <p>"A budget is telling your money where to go instead of wondering where it went"</p>
                  <footer><a href="#">View Details &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
          <li class="one_quarter">
            <article>
              <figure><img src="{% static 'Tumainibase/images/admin2.gif' %}" width="225" height="220" alt="">
                <figcaption>
                  <h2>Treasurer</h2>
                  <p>"Someone is sitting in the shade today because someone planted a tree a long time ago"</p>
                  <footer><a href="#">View Details &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
          <li class="one_quarter">
            <article>
              <figure><img src="{% static 'Tumainibase/images/admin3.gif' %}" width="225" height="220" alt="">
                <figcaption>
                  <h2>Secretary</h2>
                  <p>"If you can count your money you dont have a billion  dollars"</p>
                  <footer><a href="#">View Details &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
        </ul>
      </section>
      <!-- / Latest --> 
    </div>
    <!-- / content body --> 
  </div>
</div>
<!-- Footer -->
<div class="wrapper row4">
  <div id="footer" class="clear"> 
    <!-- Section One -->
    <section class="one_quarter first">
      <h2 class="title">Contact Details</h2>
      <p>You can reach us through the following numbers or post a query on our website .</p>
      <p>Tel: 0715912799<br>
        Fax: 0732857369<br>
        Email: <a href="mailto:njerudenis0@gmail.com?Subject=mailfromTumainiSacco">njerudenis0@gmail.com</a></p>
    </section>
    <!-- Section Two -->
    <section class="one_quarter">
      <h2 class="title">Loans</h2>
      <nav>
        <ul>
          <li class="first">Biashara loan</li>
          <li>Makeover loan</li>
          <li>Salary advance</li>
          <li>Insurance premium finance loan</li>
          <li>Emergency loan, School fees loan</li>
        </ul>
      </nav>
    </section>
    <!-- Section Three -->
    <section class="one_quarter">
      <h2 class="title">From The Blog</h2>
      <article>
        <header>
          <h2>Blog Post Title</h2>
          <time datetime="2018-02-01">Thursday, 1<sup>th</sup> Feburuary 2018</time>
        </header>
        <p>One of the best sacco's around have very low rates in their loans and savings plan are the best.</p>
        <p><a href="#">Read More &raquo;</a></p>
      </article>
    </section>
    <!-- Section Four -->
    <section class="one_quarter">
      <h2 class="title">Grab Our Newsletter</h2>
      <form method="post" action="#">
        <fieldset>
          <legend>Contact Form:</legend>
          <label for="nl_name">Name:</label>
          <input type="text" name="nl_name" id="nl_name" value="">
          <label for="nl_email">Email:</label>
          <input type="text" name="nl_email" id="nl_email" value="">
          <button type="submit" value="submit">Submit</button>
        </fieldset>
      </form>
    </section>
    <!-- / Section --> 
  </div>
</div>
<!-- Copyright -->
<div class="wrapper row5">
  <footer id="copyright" class="clear">
    <p class="fl_left">Copyright &copy; 2018 - All Rights Reserved - <a href="#">Tumaini @Co</a></p>
   
  </footer>
</div>
<script>
$(document).ready(function () {
    $("#nl_name, #nl_email").defaultvalue("Name", "Email Address");
});
</script>
</body>
</html>

Tumainibase/templates/Tumainibase/registration.html
<!DOCTYPE html>
{% extends  "Tumainibase/base.html" %}
<html>
{% block content %}
<h1>Content goes here</h1>
{% endblock %}
</html>

Tumainibase/templates/base.html
<!DOCTYPE html>

<html>
<head>
<title>TUMAINI SACCO</title>
<meta charset="iso-8859-1">
<link rel="icon" type="image/png" href="Tumainibase//favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="Tumainibase//favicon-16x16.png" sizes="16x16" /> 
<link rel="stylesheet" href="Tumainibase/layout/styles/layout.css" type="text/css">
<script src="Tumainibase/layout/scripts/jquery.min.js"></script>
<script src="Tumainibase/layout/scripts/jquery-defaultvalue.js"></script>
<!-- homepage slider scripts -->
<link rel="stylesheet" href="Tumainibase/layout/scripts/supersized/supersized.css" type="text/css">
<link rel="stylesheet" href="Tumainibase/layout/scripts/supersized/supersized.shutter.css" type="text/css">
<script src="Tumainibase/layout/scripts/supersized/supersized.3.2.7.js"></script>
<script src="Tumainibase/layout/scripts/supersized/supersized.shutter.min.js"></script>
<script src="Tumainibase/layout/scripts/supersized/supersized.setup.js"></script>
<!-- / homepage slider scripts -->
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
    <img src="Tumainibase/images/logosacco.png" alt="logo for the sacco"><h1><a href="index.html">T<span>umaini Sacco</span></a></h1>
      <h2>A sacco you can trust</h2>
    </div>
    <form action="#" method="post">
      <fieldset>
        <legend>Search:</legend>
        <input type="text" value="Search Our Website&hellip;" onFocus="this.value=(this.value=='Search Our Website&hellip;')? '' : this.value ;">
        <input type="image" src="Tumainibase/layout/images/search.gif" id="search" alt="Search">
      </fieldset>
    </form>
    <nav>
      <ul class="clear">
        <li class="first active"><a href="base.html">Home</a></li>
        <li><a href="Tumainibase/pages/style-demo.html">Registration</a></li>
        <li><a href="Tumainibase/pages/full-width.html">Login</a></li>
        <li><a href="#">Sacco Details</a>
          <ul>
            <li><a href="#">About Us </a></li>
            <li><a href="#">Sacco Investments</a></li>
            <li><a href="#">Contacts </a></li>
          </ul>
        </li>
        <li><a href="Tumainibase/pages/gallery.html">Gallery</a></li>
        <li><a href="Tumainibase/pages/portfolio.html">Portfolio</a></li>
      </ul>
    </nav>
  </header>
</div>
<!-- Slider -->
<div id="sliderwrap">
  <div id="slider"><a href="javascript:void(0)" id="prevslide" class="load-item"></a> <a href="javascript:void(0)" id="nextslide" class="load-item"></a></div>
</div>
<!-- / Slider --> 
<!-- content -->
<div class="wrapper row3">
  <div id="container" class="clear">
    <div id="homepage"> 
      <!-- ########################################################################################## --> 
      <!-- ########################################################################################## --> 
      <!-- Services -->
      <section id="services">
        <ul class="clear">
          <li class="one_quarter first"><img src="Tumainibase/images/vision.ico" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Vision</a></h2>
              <p>To be a SACCO that empowers members for improved quality of life.</p>
            </article>
          </li>
          <li class="one_quarter"><img src="Tumainibase/images/motto.ico" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Our Motto</a></h2>
              <p>United for prosperity</p>
            </article>
          </li>
          <li class="one_quarter"><img src="Tumainibase/images/mission.ico" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Mission</a></h2>
              <p>To facilitate the mobilization of savings and provision of cost effective financial and non-financial products and services to our members and customers in Kenya and beyond.</p>
            </article>
          </li>
          <li class="one_quarter"><img src="Tumainibase/images/savings.ico" width="32" height="32" alt="">
            <article>
              <h2><a href="#">Savings</a></h2>
              <p>We have various savings accounts that suits Kenya market.Visit any of our branches country wide and start saving today</p>
            </article>
          </li>
        </ul>
      </section>
      <!-- / Services --> 
      <!-- ########################################################################################## --> 
      <!-- ########################################################################################## --> 
      <!-- Shout -->
      <section id="shout">
        <p><strong>&ldquo; Well managed Sacco's can be the saving grace of the community &bdquo;</strong></p>
      </section>
      <!-- / Shout --> 
      <!-- ########################################################################################## --> 
      <!-- ########################################################################################## --> 
      <!-- Latest -->
      <section id="latest">
        <ul class="clear">
          <li class="one_quarter first">
            <h1>A word from ;</h1>
            <p>Just a few words from  some of the officials in the sacco .</p>
          </li>
          <li class="one_quarter">
            <article>
              <figure><img src="Tumainibase/images/admin1.gif" width="225" height="220" alt="">
                <figcaption>
                  <h2>CFO</h2>
                  <p>"A budget is telling your money where to go instead of wondering where it went"</p>
                  <footer><a href="#">View Details &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
          <li class="one_quarter">
            <article>
              <figure><img src="Tumainibase/images/admin2.gif" width="225" height="220" alt="">
                <figcaption>
                  <h2>Treasurer</h2>
                  <p>"Someone is sitting in the shade today because someone planted a tree a long time ago"</p>
                  <footer><a href="#">View Details &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
          <li class="one_quarter">
            <article>
              <figure><img src="Tumainibase/images/admin3.gif" width="225" height="220" alt="">
                <figcaption>
                  <h2>Secretary</h2>
                  <p>"If you can count your money you dont have a billion  dollars"</p>
                  <footer><a href="#">View Details &raquo;</a></footer>
                </figcaption>
              </figure>
            </article>
          </li>
        </ul>
      </section>
      <!-- / Latest --> 
    </div>
    <!-- / content body --> 
  </div>
</div>
<!-- Footer -->
<div class="wrapper row4">
  <div id="footer" class="clear"> 
    <!-- Section One -->
    <section class="one_quarter first">
      <h2 class="title">Contact Details</h2>
      <p>You can reach us through the following numbers or post a query on our website .</p>
      <p>Tel: 0715912799<br>
        Fax: 0732857369<br>
        Email: <a href="mailto:njerudenis0@gmail.com?Subject=mailfromTumainiSacco">njerudenis0@gmail.com</a></p>
    </section>
    <!-- Section Two -->
    <section class="one_quarter">
      <h2 class="title">Loans</h2>
      <nav>
        <ul>
          <li class="first">Biashara loan</li>
          <li>Makeover loan</li>
          <li>Salary advance</li>
          <li>Insurance premium finance loan</li>
          <li>Emergency loan, School fees loan</li>
        </ul>
      </nav>
    </section>
    <!-- Section Three -->
    <section class="one_quarter">
      <h2 class="title">From The Blog</h2>
      <article>
        <header>
          <h2>Blog Post Title</h2>
          <time datetime="2018-02-01">Thursday, 1<sup>th</sup> Feburuary 2018</time>
        </header>
        <p>One of the best sacco's around have very low rates in their loans and savings plan are the best.</p>
        <p><a href="#">Read More &raquo;</a></p>
      </article>
    </section>
    <!-- Section Four -->
    <section class="one_quarter">
      <h2 class="title">Grab Our Newsletter</h2>
      <form method="post" action="#">
        <fieldset>
          <legend>Contact Form:</legend>
          <label for="nl_name">Name:</label>
          <input type="text" name="nl_name" id="nl_name" value="">
          <label for="nl_email">Email:</label>
          <input type="text" name="nl_email" id="nl_email" value="">
          <button type="submit" value="submit">Submit</button>
        </fieldset>
      </form>
    </section>
    <!-- / Section --> 
  </div>
</div>
<!-- Copyright -->
<div class="wrapper row5">
  <footer id="copyright" class="clear">
    <p class="fl_left">Copyright &copy; 2018 - All Rights Reserved - <a href="#">Tumaini @Co</a></p>
   
  </footer>
</div>
<script>
$(document).ready(function () {
    $("#nl_name, #nl_email").defaultvalue("Name", "Email Address");
});
</script>
</body>
</html>